config/routes.rb
QuizReader::Application.routes.draw do
  
  root to: 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  match '/signup',  to: 'users#new', via: [:get, :post]
  match '/signin',  to: 'sessions#new', :as => 'signin', via: [:get, :post]
  match '/signout', to: 'sessions#destroy', via: :delete

  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save :do_before_save

	attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

	validates :password, presence: true, length: { minimum: 6 }, confirmation: true, if: :password_digest_changed?
  validates :name, presence: true, length: { maximum: 50 }


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  private

  def do_before_save
    self.remember_token ||= SecureRandom.urlsafe_base64
    self.email = self.email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
    redirect_to @current_user if signed_in?
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:session][:name].downcase) ||
           User.find_by_account_name(params[:session][:name].downcase)

    if user && user.authenticate(params[:session][:password])
      sign_in user
      if params[:email_request_key]
        redirect_to controller: :users, action: :confirm_email, key: params[:email_request_key]
      else
        redirect_to user
      end
    else
      flash.now[:error] = t 'signin.error'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
    if signed_in?
      redirect_to @current_user
    else
      render 'static_pages/home'
    end
  end

  def help
  end

  def about
  end

  def contact	
  end

  def privacy
  end

  def tos
  end


  def videos
  end

  def page404
  	render '404'
  end

  def page500
  	render '500'
  end

  def robots
  	if is_main_proudction?
	  	robots = File.read(Rails.root + "config/robots/production.txt")
	  else
	  	robots = File.read(Rails.root + "config/robots/development.txt")
	  end
	  Rails.logger.info "Is is_main_proudction? #{is_main_proudction?}"
	  render :text => robots, :layout => false, :content_type => "text/plain"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
    redirect_to root_url
  end

  def show
  	@user = User.find(request[:id])
  end

  def new
    redirect_to @current_user if signed_in?
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; QuizReader 2013</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">QuizReader</a>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "New Account", signup_path  %></li>
          <li><%= link_to "Link2", "/path2" %></li>
          <li><%= link_to "Sign off", signout_path, method: 'delete' %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "QuizReader" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render 'layouts/header' %>    

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

        <%= render 'layouts/footer' %>    

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <%= t('shared.errors', count: pluralize(object.errors.count, t('shared.error_noun'))) %>
  </div>
  <ul class="unstyled">
  <% object.errors.full_messages.each do |msg| %>
    <li class="text-error"><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_feedback_form.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t 'feedback.link' %> <b class="caret"></b>
  </a>
  <ul id="feedback-dropdown" class="dropdown-menu input-xlarge">
    <div id="feedback-background" class="well">
      <%= form_for Feedback.new, remote: true, html: { :'data-type' => 'html', id: 'feedback_form' } do |f| %>

        <legend><%= t('feedback.title') %></legend>
        <%= f.text_area :message, rows: 3 %>
        <div id="validation_error"></div>

        <%= f.hidden_field :page, value: "#{@current_controller}##{@current_action}" %>
        <%= f.hidden_field :name, value: @current_user.name  %>
        <%= f.hidden_field :email, value: @current_user.email %>
        <%= f.hidden_field :account_name, value: @current_user.account_name %>

        <label class="pull-left checkbox" style="margin-top: 7px;">
          <%= check_box_tag :anonymous, 1 %> <%= t 'feedback.anonymous' %>
        </label>

        <%= f.submit  t('feedback.button'), class: "pull-right btn btn-primary" %>

        <div class="clearfix"></div>
      <% end %>
    </div>
  </ul>
</li>

app/views/shared/_popovers.html.erb
<script type="text/javascript">

<% if @progress[:next_task] == :confirm_email %>
  var tour = new Tour({ name: "confirm_email", labels: { end: "Dismiss" } });
  tour.addSteps([{
    element: "#fat-menu",
    title: "<%= t 'tour.confirm_email_title' %>",
    content: "<%= t 'tour.confirm_email_content' %>",
    placement: "bottom",
  }]);

  $("#fat-menu").click(function() {
    tour.end();
  });

<% elsif @progress[:next_task] == :cloud_storage %>
  var tour = new Tour({ name: "cloud_storage", labels: { end: "Dismiss" } });
  tour.addSteps([{
    element: "#fat-menu",
    title: "<%= t 'tour.cloud_storage_title' %>",
    content: "<%= t 'tour.cloud_storage_content' %>",
    placement: "bottom",
  }]);

  $("#fat-menu").click(function() {
    tour.end();
  });

<% elsif @progress[:next_task] == :create_map %>
  var tour = new Tour({ name: "create_map", labels: { end: "Dismiss" } });
  tour.addSteps([{
    element: "#users_create_map",
    title: "<%= t 'tour.create_map_title' %>",
    content: "<%= t 'tour.create_map_content' %>",
    placement: "bottom",
  }]);

  $("#users_create_map").click(function() {
    tour.end();
  });

<% end %>

tour.start();
</script>

app/views/static_pages/404.html.erb
<div class="center hero-unit">
	
  <h2 class="span4" >Sorry, we could not locate the page you are trying to view.</h2>

  <h2 class="muted">404 Error</h2>

  <a href="/" class="btn btn-large btn-primary">Go Home</a>
</div>

app/views/static_pages/500.html.erb
<div class="center hero-unit">

  <h2 class="span4" >Sorry, something broke on our end.</h2>

  <h2 class="muted">500 Error</h2>

  <a href="/" class="btn btn-large btn-primary">Go Home</a>
</div>	

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>About text</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Contact Text</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Help Text</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Home</h1>

  <h2 class="muted">Home Text</h2>

  <%= link_to 'Sign up', signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/launchpage.html.erb
<div class="center vspace30">

  <div class="row">
    <span class="span12  large center">
      <h1 style="font-size:400%;">TeacherMaps</h1>
      <h3 style="font-weight:normal;">Start planning today! <%= link_to 'Sign up now', signup_path %></h3>
    </span>
    <% if false %>
      <span class="span6">
        <div class="video-container">
          <object type="application/x-shockwave-flash"
                  style="width:500px; height:300px;"
                  data="https://www.youtube.com/v/YlL3OtHKrcs&hl=en_US&start=7">
                  <param name="movie" value="https://www.youtube.com/v/YlL3OtHKrcs&hl=en_US&start=7" />
          </object>
        </div>
      </span>
    <% end %>
  </div>
</div>

<div class="content vspace10">
  <div class="container theme">

    <!-- Pay Off -->
    <div class="row center">
      <div class="span12">
        <h1><span>Navigate the world of lesson planning!</span></h1>
        <p>Create, share, and discover standard aligned curriculum maps.</p>
      </div>
    </div>
    <!-- /Pay Off -->

    <!-- Services -->
    <div class="row vspace10">

      <div class="span4 service center">
        <p><i class="icon-4x icon-rocket"></i></p>
        <h3>Create</h3>
        <p>
          Create “backwards-planned” standard-aligned unit maps quickly and easily using resources and assessments from your collection.
        </p>
      </div>

      <div class="span4 service center">
        <p><i class="icon-4x icon-cloud-upload"></i></p>
        <h3>Share</h3>
        <p>Share your best maps with other educators around the country to have an impact in their classrooms.</p>
      </div>

      <div class="span4 service center">
        <p><i class="icon-4x icon-beaker"></i></p>
        <h3>Discover</h3>
        <p>
          Discover fully featured maps from other educators that include standards, objectives, and all the resources you need to teach great lessons.
        </p>
      </div>

    </div>
    <!-- /Services -->

    <hr/>

    <!-- Content -->
    <div class="row vspace70">
      <div class="span6 center thumbnail">
        <%= image_tag 'cloud-storage.png' %>
      </div>

      <div class="span5">
        <h2>Google Drive &amp; Dropbox Integration</h2>
        <div>
          <p>TeacherMaps helps you get organized by syncing with the services you already use to store your files.</p>
          <p>Simply select Google Drive or Dropbox, copy your resources to the correct folder, and you’ll be ready to create maps in no time.</p>
          <!-- <a class="btn-theme">Read more</a> -->
        </div>
      </div>
    </div>

    <div class="row vspace30">
      <div class="span5">
        <h2>Standard Aligned</h2>
        <div>
          <p>Standards are the heart of any good unit plan. Fortunately, TeacherMaps already has Common Core standards built in! Simply select your subject and grade level, then choose the appropriate standards from our database. Organizing your curriculum around standards has never been this easy.</p>
          <!-- <a class="btn-theme">Read more</a> -->
        </div>
      </div>

      <div class="span6 center thumbnail">
        <%= image_tag 'standards.png' %>
      </div>
    </div>
    <!-- /Content -->



    <% if false %>
    <!-- Last Works -->
    <div class="row center vspace30">
      <h1><span>Hot Maps!</span></h1>
      <p>Here are some maps that star teachers have made!</p>
    </div>

    <div class="row vspace30">
      <div class="span12">
        <ul class="thumbnails">
          <li class="span3">
            <div class="thumbnail center">
              <a href="#" class="thumbnail-overlay" style="opacity: 0;"></a>
              <%= image_tag 'work_01.jpg' %>
              <div class="caption">
                <h5>Work label</h5>
                <i>Sed ut perspiciatis unde omnis iste.</i>
              </div>
            </div>
          </li>

          <li class="span3">
            <div class="thumbnail center">
              <a href="#" class="thumbnail-overlay" style="opacity: 0;"></a>
              <%= image_tag 'work_02.jpg' %>
              <div class="caption">
                <h5>Project label</h5>
                <i>Sed ut perspiciatis unde omnis iste.</i>
              </div>
            </div>
          </li>

          <li class="span3">
            <div class="thumbnail center">
              <a href="#" class="thumbnail-overlay" style="opacity: 0;"></a>
              <%= image_tag 'work_03.jpg' %>
              <div class="caption">
                <h5>Something label</h5>
                <i>Sed ut perspiciatis unde omnis iste.</i>
              </div>
            </div>
          </li>

          <li class="span3">
            <div class="thumbnail center">
              <a href="#" class="thumbnail-overlay" style="opacity: 0;"></a>
              <%= image_tag 'work_01.jpg' %>
              <div class="caption">
                <h5>Something Else</h5>
                <i>Sed ut perspiciatis unde omnis iste.</i>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <!-- Last Works -->

    <!-- Clients -->
    <div class="row center vspace30">
      <h1><span>Star/Rising Teachers</span></h1>
      <p>here are some of the teacher who are awesome at creating Maps!</p>
    </div>

    <div class="row vspace30">
      <div class="span2">
        <div class="customer"><%= image_tag 'client.png', size: '120x120' %></div>
      </div>

      <div class="span2">
        <div class="customer"><%= image_tag 'client.png', size: '120x120' %></div>
      </div>

      <div class="span2">
        <div class="customer"><%= image_tag 'client.png', size: '120x120' %></div>
      </div>

      <div class="span2">
        <div class="customer"><%= image_tag 'client.png', size: '120x120' %></div>
      </div>

      <div class="span2">
        <div class="customer"><%= image_tag 'client.png', size: '120x120' %></div>
      </div>

      <div class="span2">
        <div class="customer"><%= image_tag 'client.png', size: '120x120' %></div>
      </div>
    </div>
    <!-- /Clients -->
    <% end %>

  </div>
</div>

<footer id="footer">
  <div id="post-footer">
    <div class="container">
      <div class="row center">
        <div class="span12">
          <div class="vspace10">
          <div>Follow us<div>
            <a href="https://twitter.com/teachermaps"><i class="icon-twitter icon-2x theme" ></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/static_pages/privacy.html.erb
<h1>Privacy policy</h1>

app/views/static_pages/tos.html.erb
<h1>TeacherMaps Terms of Service</h1>
<p>Last modified: May 6, 2013</p>

<h3>Welcome to TeacherMaps!</h3>

<p>
  Thanks for using our products and services (“Services”). The Services
  are provided by TeacherMaps Inc. (“TeacherMaps”), located at
  3020 Mountain Lion Drive #204, Loveland, CO 80537, United States.
  </p>

<p>
  By using our Services, you are agreeing to these terms. Please read them carefully.
</p>

<p>
  Our Services are very diverse, so sometimes additional terms or
  product requirements (including age requirements) may apply.
  Additional terms will be available with the relevant Services, and
  those additional terms become part of your agreement with us if you
  use those Services.
</p>

<h3>Using our Services</h3>

<p>
  You must follow any policies made available to you within the Services.
</p>

<p>
  Don’t misuse our Services. For example, don’t interfere with our
  Services or try to access them using a method other than the interface
  and the instructions that we provide. You may use our Services only
  as permitted by law, including applicable export and re-export
  control laws and regulations. We may suspend or stop providing our
  Services to you if you do not comply with our terms or policies or
  if we are investigating suspected misconduct.
</p>

<p>
  Using our Services does not give you ownership of any intellectual
  property rights in our Services or the content you access. You may
  not use content from our Services unless you obtain permission from
  its owner or are otherwise permitted by law. These terms do not
  grant you the right to use any branding or logos used in our
  Services. Don’t remove, obscure, or alter any legal notices displayed
  in or along with our Services.
</p>

<p>
  Our Services display some content that is not TeacherMaps’s. This
  content is the sole responsibility of the entity that makes it
  available. We may review content to determine whether it is illegal
  or violates our policies, and we may remove or refuse to display
  content that we reasonably believe violates our policies or the law.
  But that does not necessarily mean that we review content, so please
  don’t assume that we do.
</p>

<p>
  In connection with your use of the Services, we may send you service
  announcements, administrative messages, and other information. You may
  opt out of some of those communications.
</p>

<h3>Your TeacherMaps Account</h3>

<p>
  You may need a TeacherMaps Account in order to use some of our
  Services. You may create your own TeacherMaps Account, or your
  TeacherMaps Account may be assigned to you by an administrator, such
  as your employer or educational institution. If you are using a
  TeacherMaps Account assigned to you by an administrator, different or
  additional terms may apply and your administrator may be able to
  access or disable your account.
</p>

<p>
  If you learn of any unauthorized use of your password or account,
  <%= link_to 'contact us', controller: 'static_pages', action: 'contact' %>.
</p>

<h3>Privacy and Copyright Protection</h3>

<p>
  TeacherMaps’s
  <%= link_to 'privacy policy', controller: 'static_pages', action: 'privacy' %>
  explain how we treat your personal data and protect your privacy when
  you use our Services. By using our Services, you agree that TeacherMaps
  can use such data in accordance with our privacy policies.
</p>

<p>
  We respond to notices of alleged copyright infringement and terminate
  accounts of repeat infringers according to the process set out in the
  U.S. Digital Millennium Copyright Act.
</p>

<p>
  We provide information to help copyright holders manage their
  intellectual property online. If you think somebody is violating your
  copyrights and want to notify us, please
  <%= link_to 'contact us', controller: 'static_pages', action: 'contact' %>.
</p>

<h3>Your Content in our Services</h3>

<p>
  Some of our Services allow you to submit content. You retain
  ownership of any intellectual property rights that you hold in that
  content. In short, what belongs to you stays yours.
</p>

<p>
  When you upload or otherwise submit content to our Services, you give
  TeacherMaps (and those we work with) a worldwide license to use,
  host, store, reproduce, modify, create derivative works (such as
  those resulting from translations, adaptations or other changes we
  make so that your content works better with our Services),
  communicate, publish, publicly perform, publicly display and
  distribute such content. The rights you grant in this license are for
  the limited purpose of operating, promoting, and improving our
  Services, and to develop new ones. This license continues even if you
  stop using our Services (for example, for a map you have added to
  TeacherMaps). Some Services may offer you ways to access
  and remove content that has been provided to that Service. Also, in
  some of our Services, there are terms or settings that narrow the
  scope of our use of the content submitted in those Services. Make
  sure you have the necessary rights to grant us this license for any
  content that you submit to our Services.
</p>

<p>
  You can find more information about how TeacherMaps uses and stores
  content in the
  <%= link_to 'privacy policy', controller: 'static_pages', action: 'privacy' %>.
  If you submit feedback or suggestions about our Services, we may use
  your feedback or suggestions without obligation to you.
</p>

<h3>About Software in our Services</h3>

<p>
  When a Service requires or includes downloadable software, this
  software may update automatically on your device once a new version
  or feature is available. Some Services may let you adjust your
  automatic update settings.
</p>

<p>
  TeacherMaps gives you a personal, worldwide, royalty-free,
  non-assignable and non-exclusive license to use the software
  provided to you by TeacherMaps as part of the Services. This
  license is for the sole purpose of enabling you to use and enjoy
  the benefit of the Services as provided by TeacherMaps, in the manner
  permitted by these terms. You may not copy, modify, distribute, sell,
  or lease any part of our Services or included software, nor may you
  reverse engineer or attempt to extract the source code of that
  software, unless laws prohibit those restrictions or you have our
  written permission.
</p>

<p>
  Open source software is important to us. Some software used in our
  Services may be offered under an open source license that we will make
  available to you. There may be provisions in the open source license
  that expressly override some of these terms.
</p>

<h3>Modifying and Terminating our Services</h3>

<p>
  We are constantly changing and improving our Services. We may add or
  remove functionalities or features, and we may suspend or stop a Service altogether.
</p>

<p>
  You can stop using our Services at any time, although we’ll be sorry
  to see you go. TeacherMaps may also stop providing Services to you,
  or add or create new limits to our Services at any time.
</p>

<p>
  We believe that you own your data and preserving your access to such
  data is important. If we discontinue a Service, where reasonably
  possible, we will give you reasonable advance notice and a chance to
  get information out of that Service.
</p>

<h3>Our Warranties and Disclaimers</h3>

<p>
  We provide our Services using a commercially reasonable level of
  skill and care and we hope that you will enjoy using them. But there
  are certain things that we don’t promise about our Services.
</p>

<p>
  OTHER THAN AS EXPRESSLY SET OUT IN THESE TERMS OR ADDITIONAL TERMS,
  NEITHER TEACHERMAPS NOR ITS SUPPLIERS OR DISTRIBUTORS MAKE ANY
  SPECIFIC PROMISES ABOUT THE SERVICES. FOR EXAMPLE, WE DON’T MAKE ANY
  COMMITMENTS ABOUT THE CONTENT WITHIN THE SERVICES, THE SPECIFIC
  FUNCTION OF THE SERVICES, OR THEIR RELIABILITY, AVAILABILITY, OR
  ABILITY TO MEET YOUR NEEDS. WE PROVIDE THE SERVICES “AS IS”.
</p>

<p>
  SOME JURISDICTIONS PROVIDE FOR CERTAIN WARRANTIES, LIKE THE IMPLIED
  WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NON-INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL WARRANTIES.
</p>

<h3>Liability for our Services</h3>

<p>
  WHEN PERMITTED BY LAW, TEACHERMAPS, AND TEACHERMAPS’S SUPPLIERS AND
  DISTRIBUTORS, WILL NOT BE RESPONSIBLE FOR LOST PROFITS, REVENUES, OR
  DATA, FINANCIAL LOSSES OR INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY,
  OR PUNITIVE DAMAGES.
</p>

<p>
  TO THE EXTENT PERMITTED BY LAW, THE TOTAL LIABILITY OF TEACHERMAPS,
  AND ITS SUPPLIERS AND DISTRIBUTORS, FOR ANY CLAIM UNDER THESE TERMS,
  INCLUDING FOR ANY IMPLIED WARRANTIES, IS LIMITED TO THE AMOUNT YOU
  PAID US TO USE THE SERVICES (OR, IF WE CHOOSE, TO SUPPLYING YOU THE
  SERVICES AGAIN).
</p>

<p>
  IN ALL CASES, TEACHERMAPS, AND ITS SUPPLIERS AND DISTRIBUTORS, WILL
  NOT BE LIABLE FOR ANY LOSS OR DAMAGE THAT IS NOT REASONABLY FORESEEABLE.
</p>

<h3>Business uses of our Services</h3>

<p>
  If you are using our Services on behalf of a business, that business
  accepts these terms. It will hold harmless and indemnify TeacherMaps
  and its affiliates, officers, agents, and employees from any claim,
  suit or action arising from or related to the use of the Services or
  violation of these terms, including any liability or expense arising
  from claims, losses, damages, suits, judgments, litigation costs and attorneys’ fees.
</p>

<h3>About these Terms</h3>

<p>
  We may modify these terms or any additional terms that apply to a
  Service to, for example, reflect changes to the law or changes to our
  Services. You should look at the terms regularly. We’ll post notice of
  modifications to these terms on this page. Changes will not apply
  retroactively and will become effective no sooner than fourteen days
  after they are posted. However, changes addressing new functions for
  a Service or changes made for legal reasons will be effective
  immediately. If you do not agree to the modified terms for a Service,
  you should discontinue your use of that Service.
</p>

<p>
  If there is a conflict between these terms and the additional terms,
  the additional terms will control for that conflict.
</p>

<p>
  These terms control the relationship between TeacherMaps and you.
  They do not create any third party beneficiary rights.
</p>

<p>
  If you do not comply with these terms, and we don’t take action
  right away, this doesn’t mean that we are giving up any rights that
  we may have (such as taking action in the future).
</p>

<p>
  If it turns out that a particular term is not enforceable, this will
  not affect any other terms.
</p>

<p>
  The laws of California, U.S.A., excluding California’s conflict of
  laws rules, will apply to any disputes arising out of or relating to
  these terms or the Services. All claims arising out of or relating to
  these terms or the Services will be litigated exclusively in the
  federal or state courts of Santa Clara County, California, USA, and
  you and TeacherMaps consent to personal jurisdiction in those courts.
</p>

<p>
  For information about how to contact TeacherMaps, please visit our
  <%= link_to 'contact page', controller: 'static_pages', action: 'contact' %>.
</p>

app/views/users/new.html.erb
<h1 class="center"><%= 'New Account' %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { object: @user } %>

      <%= f.label :name, 'Full Name' %>
      <%= f.text_field :name %>

      <%= f.label :email, 'Email' %>
      <%= f.text_field :email %>

      <%= f.label :password, 'Password' %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, 'Password Confirmation' %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit 'Sign Up', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>
<%= @user.email %>